apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      compoment: postgres
  template:
    metadata:
      labels:
        compoment: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim #from the other file
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data 
            subPath: postgres #particular to postgres
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD